development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://hpecmrxfnkawml:4a164be1046cce1dd19d0f431bc8d2f0ae2bd5fbf9f1d3177e735f62972e8d94@ec2-54-225-115-234.compute-1.amazonaws.com:5432/d82sk4mrm14a3q
  channel_prefix: myapp_production
